[package]
name = "kamipad"
version = "0.1.0"
authors = ["Ricardo B. Machado <ricardobm@gmail.com>"]
license = "MIT"
description = "Personal notepad (server)"
repository = "https://github.com/ricardobm/kamipad/"
keywords = ["note", "editor"]


[dependencies]
